name: Deploy to VPS

on:
  push:
    branches:
      - main  # Déclenche sur push vers main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 3 : Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Étape 4 : Construire et pousser l’image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/xtracto-io:latest

      # Étape 5 : Déployer sur le VPS via SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            # Connexion à Docker Hub
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            # Supprimer l’ancien conteneur s’il existe
            docker stop xtracto-container || true
            docker rm xtracto-container || true
            # Tirer la nouvelle image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/xtracto-io:latest
            # Exécuter le conteneur avec le fichier d’environnement
            docker run -d --name xtracto-container \
              -p 8002:8002 \
              -v /home/ubuntu/xtracto-io:/app/src/environment \
              ${{ secrets.DOCKERHUB_USERNAME }}/xtracto-io:latest