name: Deploy to VPS

on:
  push:
    branches:
      - main  # Déclenche sur push vers main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 3 : Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Étape 4 : Construire et pousser l’image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/xtracto-io:latest

      # Étape 5 : Déployer sur le VPS via SSH avec mot de passe
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3  # Version plus récente
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22  # Mettez à jour si nécessaire
          timeout: 60s  # Augmenté pour plus de fiabilité
          script_stop: true
          debug: true  # Ajouté pour plus de logs
          script: |
            echo "Démarrage du script de déploiement"
            # Vérifier la connexion SSH
            whoami || { echo "Erreur SSH"; exit 1; }
            
            # Connexion à Docker Hub
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} || { echo "Erreur Docker login"; exit 1; }
            
            # Supprimer l’ancien conteneur s’il existe
            docker stop xtracto-container || true
            docker rm xtracto-container || true
            
            # Créer le répertoire avec les bonnes permissions
            mkdir -p /home/ubuntu/xtracto-io || { echo "Erreur création répertoire"; exit 1; }
            chown ubuntu:ubuntu /home/ubuntu/xtracto-io || { echo "Erreur changement propriétaire"; exit 1; }
            chmod 700 /home/ubuntu/xtracto-io || { echo "Erreur changement permissions"; exit 1; }
            
            # Copier prod.env dans le répertoire de l’application
            echo "ENVIRONMENT=prod" > /home/ubuntu/xtracto-io/prod.env
            echo "MONGO_URI=mongodb://admin:(D937k{£j6kWJBd}C)/a@localhost:27017/xtractio?authSource=admin" >> /home/ubuntu/xtracto-io/prod.env
            echo "AWS_S3_BUCKET_NAME=cercina-real-estate-files" >> /home/ubuntu/xtracto-io/prod.env
            echo "AWS_S3_ENDPOINT=https://s3.eu-central-003.backblazeb2.com" >> /home/ubuntu/xtracto-io/prod.env
            echo "AWS_S3_ACCESS_KEY=003a8db8fe4620d0000000001" >> /home/ubuntu/xtracto-io/prod.env
            echo "AWS_S3_SECRET_KEY=K003ytmOR03jy31uqTleH6xPGYfN0" >> /home/ubuntu/xtracto-io/prod.env
            echo "KAMELEO_HOST=192.168.122.33" >> /home/ubuntu/xtracto-io/prod.env
            echo "KAMELEO_PORT=5001" >> /home/ubuntu/xtracto-io/prod.env
            chown ubuntu:ubuntu /home/ubuntu/xtracto-io/prod.env
            chmod 600 /home/ubuntu/xtracto-io/prod.env
            
            # Tirer la nouvelle image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/xtracto-io:latest || { echo "Erreur pull image"; exit 1; }
            
            # Exécuter le conteneur
            docker run -d --name xtracto-container \
              -p 8002:8002 \
              -v /home/ubuntu/xtracto-io:/app/src/environment \
              -e ENVIRONMENT=prod \
              -e MONGO_URI=${{ secrets.MONGO_URI }} \
              -e AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }} \
              -e AWS_S3_ENDPOINT=${{ secrets.AWS_S3_ENDPOINT }} \
              -e AWS_S3_ACCESS_KEY=${{ secrets.AWS_S3_ACCESS_KEY }} \
              -e AWS_S3_SECRET_KEY=${{ secrets.AWS_S3_SECRET_KEY }} \
              -e KAMELEO_HOST=192.168.122.33 \
              -e KAMELEO_PORT=5001 \
              ${{ secrets.DOCKERHUB_USERNAME }}/xtracto-io:latest || { echo "Erreur lancement conteneur"; exit 1; }
            
            # Vérifier que le conteneur est en cours d’exécution
            docker ps -a | grep xtracto-container || { echo "Conteneur non démarré"; exit 1; }
            echo "Déploiement terminé avec succès"